### ISSUE TITLE
Null Ref Exception at Web App startup

### ISSUE THREAD

**Issue by kirill-lappo-dgt** [IzyPro/WatchDog#105]
**Description**
Null reference exceptions is falling at web app startup.

At line 92.

https://github.com/IzyPro/WatchDog/blob/f0ad08186f4bc0ecd9c93e735dec366c2a6ff135/WatchDog/src/WatchLogger.cs#L75-L93

It happens because of a 3d party package, which creates log event in its constructor (don't even ask why, 
 I would like to know that too 😓). 

This happens even before `Startup.ConfugreServices()` and `Startup.Configure()` methods are called,
so `ServiceProviderFactory.BroadcastHelper` is null at the moment of a call - because it will be initialized only in `WatchDogExtension.AddWatchDog(this IApplicationBuilder app, Action<WatchDogOptionsModel> configureOptions)` method.

Our project uses dotnet 6, but we still use web host creation of net core 3.

**Details (please complete the following information):**
 - Project Type: MVC
 - Framework Version: .NET 6
 - WatchDog Version: 1.4.2
 - Database: MSSQL

**Comment by fmd-aggne** [comment]
This is currently a showstopper. Please release v1.4.3 so we can have this fix.

**Comment by IzyPro** [comment]
This issue is being closed as it has been fixed
Kindly update your WatchDog package
