### ISSUE TITLE
Remove unnecesary libraries

### ISSUE THREAD

**Issue by dlopezpl** [IzyPro/WatchDog#115]
Firs things first. Excelent library.
Could it be possible to remove the references to data access libraries?

If I don´t want to use external DB, I wouldn´t like to have all that references installed.
Thanks

**Comment by Khelechy** [comment]
We really appreciate your feedback. The package currently supports flexibility for different DBs , and is currently bundled into one, this makes it difficult to have a selective/optional installation for reference libraries. While we dont have plans to create separate libraries for different DBs ATM, we indulge you to bare with us with the current implementation, as this doesn't pose as a blocker for the usage of the library.  We are definitely working to reduce the size further.
