### ISSUE TITLE
not load index page in razor pages

### ISSUE THREAD

**Issue by AbbasHokmabadi71** [IzyPro/WatchDog#117]
**Description**
After making the settings according to the documentation, after running the project, the index page will be white

**Details (please complete the following information):**
 - Project Type: razor page
 - Framework Version  .NET 7
 - WatchDog Version latest
 - Database mssql
 - Browser Chrome, Edge

**Comment by IzyPro** [comment]
Hi @AbbasHokmabadi71 
This sounds similar to issues in [this trail](https://github.com/IzyPro/WatchDog/issues/97) 
Let us know if those solutions do not work for you.

**Comment by AbbasHokmabadi71** [comment]
adding `app.UseMvcWithDefaultRoute()` to program.cs
its ok.

**Comment by IzyPro** [comment]
That’s great to hear
