### ISSUE TITLE
Set the location of the db file when using the default LiteDB

### ISSUE THREAD

**Issue by Shadow-XT** [IzyPro/WatchDog#123]
When I use the default LiteDB to store data, the default generated db file location is in the root directory of the project. I want to specify the location of the db file so that it won't appear so bad for project design.
By the way, will SQLite support be considered in the future.

**Comment by shoboske** [comment]
To do this it will be better to set the connection string to a different path as specified in the docs 

```

services.AddWatchDogServices(settings => 
{
   settings.SqlDriverOption = WatchDogSqlDriverEnum.LiteDb;
   settings.SetExternalDbConnString = "Filename=C:\database.db;Password=1234";
});
```

That should do the trick 👍🏿

**Comment by shoboske** [comment]
> When I use the default LiteDB to store data, the default generated db file location is in the root directory of the project. I want to specify the location of the db file so that it won't appear so bad for project design. By the way, will SQLite support be considered in the future.

To do this it will be better to set the connection string to a different path as specified in the docs 

```

services.AddWatchDogServices(settings => 
{
   settings.SqlDriverOption = WatchDogSqlDriverEnum.LiteDb;
   settings.SetExternalDbConnString = "Filename=C:\database.db;Password=1234";
});
```

That should do the trick 👍🏿
