### ISSUE TITLE
Newer requests doesn't follow the filter rule

### ISSUE THREAD

**Issue by luiz-diniz** [IzyPro/WatchDog#129]
**Description**
Request logs keeps showing newer requests that are not included on the filter (methods, status code).

**To Reproduce**
1. Access the "Request Logs" page
2. Configure a filter option
3. Click on "Search"

**Expected behavior**
I believe that once you click on the "Search" button, the list should just show newer requests that matches the filter. It may be get a little confusing to have other newer requests that doesn't match the filter coming up on the list.

**Screenshots**
Post Example
![image](https://github.com/IzyPro/WatchDog/assets/39447716/a0dbf0d8-6817-4821-8913-170b8365ec6e)

Put Example
![image](https://github.com/IzyPro/WatchDog/assets/39447716/d0334158-8bc2-467f-9a1c-7d87fcb98c02)

**Details (please complete the following information):**
 - Project Type: ASP.NET Web API
 - Framework Version: .NET 6
 - WatchDog Version: 1.4.10
 - Database: Do not apply
 - Browser: Microsoft Edge

**Comment by IzyPro** [comment]
Hi @luiz-diniz 
This issue has been fixed in the newly released v1.4.11.
