### ISSUE TITLE
BaseURL entry issue in with UsePathBase: ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by DavoBR** [IzyPro/WatchDog#130]
**Description**
I have a Blazor project deployed as an application in IIS, and I have configured the UsePathBase because the application is published within a subfolder.

When trying to access, for example, http://localhost:5000/mysubfolder, the following error is thrown: ArgumentOutOfRangeException: Index and count must refer to a location within the string. (Parameter 'count'). However, if I add a slash at the end, that is, http://localhost/mysubfolder/, it works correctly.

I noticed that the middleware is removing the first character of the request path, and since it is arriving blank, the exception is thrown.

![image](https://github.com/IzyPro/WatchDog/assets/498724/46fb5ae2-3b9c-492e-a517-674f9174399b)

**To Reproduce**
1. Add app.UsePathBase("mysubfolder")
2. Start the application
3. Open the url http://localhost:5000/mysubfolder

**Expected behavior**
It is expected that when entering the base URL without placing a slash at the end of the URL, the page should be displayed.

**Screenshots**
![image](https://github.com/IzyPro/WatchDog/assets/498724/78351bd9-08ed-4ade-968a-38ec7f851ac0)

**Details (please complete the following information):**
 - Project Type: Blazor Server
 - Framework Version .NET 7
 - WatchDog Version 1.4.10
 - Database Default
 - Browser Chrome

**Comment by IzyPro** [comment]
Hello @DavoBR 
This issue issue has been fixed in the just released v1.4.11.
Thanks for bringing it to our attention.
