### ISSUE TITLE
Blacklist using regex

### ISSUE THREAD

**Issue by AltaherPresto** [IzyPro/WatchDog#132]
**Is your feature request related to a problem? Please describe.**
I run a small microservice on an AWS ECS container and it gets a LOT of requests from spam bots.
The microservice only has 2 endpoints and needs to stay publically accessible.
I'm using Watchdog to monitor the legitimate requests but the dashboard (and database) is spammed with spam requests.

**Describe the solution you'd like**
I want the watchdog `Blacklist` feature to allow me to use regex so it only stores legitimate requests using `negative lookahead assertions` like so:

`^(?!.*\/api\/mypath).*$`

**Comment by IzyPro** [comment]
Hi @AltaherPresto 
This is now possible in the newly released v1.4.11.
You can check the documentation on how to enable regex for blacklisting.
