### ISSUE TITLE
Need to add customized column for log like userid.. 

### ISSUE THREAD

**Issue by tabhijeet1999** [IzyPro/WatchDog#135]
**Is your feature request related to a problem? Please describe.**
Need to add more column as per need and possible to override the loging method to need as per need logger just like we are doing customized filers to do as per need. 

**Describe the solution you'd like**
Use interface to do the same overriding.
.

**Comment by IzyPro** [comment]
@tabhijeet1999 could you provide a bit more clarity to your request?
