### ISSUE TITLE
OutputCache not working when watchdog is used

### ISSUE THREAD

**Issue by tnlthanzeel** [IzyPro/WatchDog#136]
**Description**
I have an API built with ASP Core 8 and i have added `OutputCache` to cache countries from a `GET `endpoint. The `OutputCache` seem to work fine. But once i add watchdog the output cache doesn't work and it always hits the API. If watch dog is commented the `OutputCache` c=works agaib

**Expected behavior**
`OutputCache` ,ust work with watchdog

**Screenshots**
![image](https://github.com/IzyPro/WatchDog/assets/18216790/335baf62-24b7-4948-be7c-e8b94f790092)

**Details (please complete the following information):**
 - Project Type: ASP Core 8 web API
 - Framework Version: .NET 8
 - WatchDog Version: 1.4.10
 - Database: MSSQL

**Comment by IzyPro** [comment]
@tnlthanzeel have you tried switching the middleware order?
For example, having `app.UseOutputCache()` come before `app.UseWatchDog()`

**Comment by tnlthanzeel** [comment]
hi @IzyPro , did you have time to check on this?

**Comment by tnlthanzeel** [comment]
@IzyPro , any update on this issue?

**Comment by IzyPro** [comment]
Hi @tnlthanzeel 
Would you be willing to help run some tests?
If you are, please reach out to me on Twitter(X) @IzyPro_

**Comment by tnlthanzeel** [comment]
Ho. Didnt have time to check on this, but this still the issue persist

**Comment by IzyPro** [comment]
Hi @tnlthanzeel 
This has now been resolved.
Update to the just released v1.4.11 and check the documentation for how to configure WatchDog when using output cache.

**Comment by tnlthanzeel** [comment]
> Hi @tnlthanzeel This has now been resolved. Update to the just released v1.4.11 and check the documentation for how to configure WatchDog when using output cache.

Thanks a lot!
