### ISSUE TITLE
UseWatchDog method stops middleware chain on not watchdog requests

### ISSUE THREAD

**Issue by jkune** [IzyPro/WatchDog#146]
When using `UseWatchDog()` any later middleware used is not invoked

**To Reproduce**
Use a dumb middleware after UseSwagger method.
```
app.Use(async (context, next) =>
{
    await next(context); // this is executed
});
app.UseWatchDog(...)
app.Use(async (context, next) =>
{
    await next(context); // this is NOT executed
});
```

**Expected behavior**
The expected behaviour is that all middlewares are invoked in requests.

**Details (please complete the following information):**
 - Project Type: API
 - Framework Version NET 7
 - WatchDog Version 1.4.10
 - Database MSSQL

**Comment by IzyPro** [comment]
Hi @jkune 
Your middleware should come before .UseWatchDog()
