### ISSUE TITLE
Property 'JsonResult.SerializerSettings' must be an instance of type 'Newtonsoft.Json.JsonSerializerSettings'

### ISSUE THREAD

**Issue by alinaeimii** [IzyPro/WatchDog#147]
hi
i want to config watchdog.net for ocelot API gateway 
but when i login to dashboard watchdog and refresh for load data from database watchdog.net i had this error:

![Screenshot 2024-04-27 234103](https://github.com/IzyPro/WatchDog/assets/10638714/a37711a1-871f-477d-8373-96c49c8d28ee)

is it bug?

**Comment by IzyPro** [comment]
Hi @alinaeimii 
Refer to https://github.com/IzyPro/WatchDog/issues/94
You need to let WatchDog know if you’re not using the default json serializer
