### ISSUE TITLE
How to set the current project LiteDB default path？

### ISSUE THREAD

**Issue by zfchai** [IzyPro/WatchDog#149]
# Use default LiteDB

Hi, how do I set the path to the directory where the LiteDB folder is stored in the current project?

```csharp
builder.Services.AddWatchDogServices(opt => {
    opt.IsAutoClear = true;

    // use the default LiteDB and set the folder directory
    char dsc = Path.DirectorySeparatorChar;
    // example => Demo\AppData\Database
    string litedbPath = $"{builder.Environment.ContentRootPath}{dsc}AppData{dsc}Database";
    opt.SetLiteDbPath = litedbPath; // Would like to add similar extension support, thanks!

    //opt.SetExternalDbConnString = "Database";
    //opt.DbDriverOption = WatchDogDbDriverEnum.PostgreSql;
});
```

Currently I can't find any local default settings that can be extended to support this feature?

**Comment by DreamTom** [comment]
you just need add  builder.Services.AddWatchDogServices(), it can use LiteDB as default

**Comment by DreamTom** [comment]
you just need add  builder.Services.AddWatchDogServices(), it can use LiteDB as default
