### ISSUE TITLE
.Net 8.0 package version problem for Microsoft.IO.RecyclableMemoryStream 

### ISSUE THREAD

**Issue by EmreKabali** [IzyPro/WatchDog#159]
In my .NET 8.0 application, I encountered an error while using the Watchdog library. The problem seems to come from a version mismatch with the Microsoft.IO.RecyclableMemoryStream package. This means that the version of this package is not fully compatible with .NET 8.0, which causes the application to throw an error.

**Comment by rkaptan** [comment]
++

**Comment by Lyfoeverxj** [comment]
+1

**Comment by Khelechy** [comment]
This has been fixed and will be pushed with the next release.
