### ISSUE TITLE
Runtime exception caused by SignalR.HubRouteBuilder

### ISSUE THREAD

**Issue by AltaherEmhemed** [IzyPro/WatchDog#30]
I created a new .NET 6 API Project, installed WatchDog from Nuget then added the configuration to `Program.cs`.
The project builds successfully but I get this exception at startup
<img width="1043" alt="WatchDog" src="https://user-images.githubusercontent.com/2446317/166062896-a0e1b5bf-54ee-41c7-a35b-8ccf845f7ae0.png">

I went and installed SignalR from Nuget, but problem persists

<img width="859" alt="image" src="https://user-images.githubusercontent.com/2446317/166063138-ce3c3694-9af6-409a-947b-3eaaf865593a.png">

**Comment by Khelechy** [comment]
Seems like a dll mismatch, we are working to get that fixed ASAP

**Comment by IzyPro** [comment]
Hi @AltaherEmhemed 
This has been fixed.
Upgrade the package to the most recent version (1.0.1) and you're good to go.
