### ISSUE TITLE
Argument Exception: Username and password required on .UseWatchLog()

### ISSUE THREAD

**Issue by AltaherEmhemed** [IzyPro/WatchDog#33]
ASP.NET 6 API Project
Project builds successfully but I get this exception at startup.

Watchdog 1.0.1 installed

<img width="892" alt="image" src="https://user-images.githubusercontent.com/2446317/166104921-a25ae588-e6cb-4198-9edc-bdf2f7336607.png">

<img width="888" alt="image" src="https://user-images.githubusercontent.com/2446317/166104991-ace6279a-f17f-42e1-a5a9-3ead08369532.png">

**Comment by IzyPro** [comment]
Hi @AltaherEmhemed 
From the screenshot of your code, I can see that you are setting the password twice.
Meaning you have no username set up.
Correct that and you should be good to go

**Comment by Khelechy** [comment]
We are marking this as closed.. Cheers

**Comment by AltaherEmhemed** [comment]
@IzyPro 
I fixed the username but now I get a DirectoryNotFound exception

<img width="989" alt="image" src="https://user-images.githubusercontent.com/2446317/166105914-7b3a7cfb-f115-4aad-88ec-79a62af4653b.png">

**Comment by IzyPro** [comment]
Hi @AltaherEmhemed 
This has been fixed and an updated version (1.1.0) has been published.
