### ISSUE TITLE
Support for dotnet 6+

### ISSUE THREAD

**Issue by seanmudbath** [IzyPro/WatchDog#45]
Is there any support for dotnet 6+?  I've attempted to use this package in a dotnet 6 project but no matter how I configure it I can't seem to get the logs to display, whether success or fail.
Dotnet 6 doesn't require app.UseRouting or app.UseEndpoints (just app.MapControllers) as per the documentation, so it isn't clear where to place app.UseWatchDog line in that scenario.

**Comment by IzyPro** [comment]
Hi @seanmudbath 
It is unclear what issue you are experiencing but I'll refer you back to the documentation. There are sample projects that you can check out and see how it was implemented.
Here's a direct link to the .NET6 project
https://github.com/IzyPro/WatchDog/tree/main/WatchDogCompleteApiNet6
