### ISSUE TITLE
 app.UseWatchDog overriding the Authorization middleware

### ISSUE THREAD

**Issue by tylndemirci** [IzyPro/WatchDog#51]
app.UseWatchDog overriding the Authorization middleware, therefore, when you try to go to a controller with Authorize attribute in it, it says you need to use app.Authorization even though there is an app.Authorization

**Comment by rkaptan** [comment]
I can't view logs of methods after authorization. I am using the Bearer method.

**Comment by tylndemirci** [comment]
> I can't view logs of methods after authorization. I am using the Bearer method.

I fixed the issue by removing app.userouting and app.build in the middleware. Try putting the useWatchDog just before useEndpoint and placing the useWatchDogExceptionLoggerin just env.IsDevelopment conditions, or try playing with the source code 
![image](https://user-images.githubusercontent.com/60180444/183158200-a9308d62-23bc-49ff-acd2-1fcdf4a6049c.png)

**Comment by rkaptan** [comment]
unfortunately it doesn't work for me.

**Comment by rkaptan** [comment]
System.InvalidOperationException: Endpoint * contains authorization metadata, but a middleware was not found that supports authorization.
      Configure your application startup by adding app.UseAuthorization() in the application startup code. If there are calls to app.UseRouting() and app.UseEndpoints(...), the call to app.UseAuthorization() must go between them.
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingAuthMiddlewareException(Endpoint endpoint)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
         at WatchDog.src.WatchDog.LogResponse(HttpContext context)
         at WatchDog.src.WatchDog.InvokeAsync(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at WatchDog.src.WatchDogExceptionLogger.InvokeAsync(HttpContext context)
         at WatchDog.src.WatchDogExceptionLogger.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
         at x.Dependency.SwaggerBasicAuthMiddleware.InvokeAsync(HttpContext context)

**Comment by tylndemirci** [comment]
It's about the second app.UseRouting() in the middleware. I guess it is making the your app.UseAuthorization();  vanish. You can also get all the middleware code from source code to your Configure() and debug it. My only advice would be to not use a second app.UseRouting()

![image](https://user-images.githubusercontent.com/60180444/183196584-00f95225-4261-4c1f-ad87-dc22ea52df5a.png)

**Comment by IzyPro** [comment]
Hi @tylndemirci @rkaptan 
It is unclear the issue you are experiencing. However, i'd like to point out that WatchDog uses .UseRouting() and .UseEndpoints() internally so if both endpoints are used in conjunction with Authorization in your codebase, you might want to move .UseWatchDog() to the last line of your middleware pipeline.
If that doesn't resolve your issue please send a more descriptive report using the below format

Description 
A clear and concise description of what the bug is.

To Reproduce 
Steps to reproduce the behavior:

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

Expected behavior 
A clear and concise description of what you expected to happen.

Screenshots 
If applicable, add screenshots to help explain your problem.

Details (please complete the following information):
- Project Type: [e.g. API, MVC]
- Framework Version [e.g. .NET Core 3.1, .NET 6]
- WatchDog Version [e.g. 1.3.0, 1.2.1]
- Database [e.g Default, MySQL]

Additional context 
Add any other context about the problem here.

**Comment by rkaptan** [comment]
public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvcCore(options => { options.Filters.Add(typeof(ValidateModelStateAttribute)); });
           
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidateAudience = true,
                    ValidateLifetime = true,
                    ValidateIssuerSigningKey = true,
                    ValidIssuer = Configuration["JwtxxxAuth:Issuer"],
                    ValidAudience = Configuration["JwtxxxAuth:Audience"],
                    RequireExpirationTime = true,
                    ClockSkew = TimeSpan.Zero,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["JwtxxxAuth:Key"]))
                };

                options.Events = new JwtBearerEvents
                {
                    OnChallenge = context =>
                    {
                        context.HandleResponse();
                        context.Response.StatusCode = StatusCodes.Status401Unauthorized;
                        context.Response.ContentType = "application/json";
                        context.Response.Headers.Add("Access-Control-Allow-Origin", "*");

                        // Ensure we always have an error and error description.
                        if (string.IsNullOrEmpty(context.Error))
                            context.Error = "Yetkisiz Erişim";
                        if (string.IsNullOrEmpty(context.ErrorDescription))
                            context.ErrorDescription = "İstek Yapabilmeniz için Token Gereklidir.";

                        // Add some extra context for expired tokens.
                        if (context.AuthenticateFailure != null && context.AuthenticateFailure.GetType() == typeof(SecurityTokenExpiredException))
                        {
                            var authenticationException = context.AuthenticateFailure as SecurityTokenExpiredException;
                            context.Response.Headers.Add("x-token-expired", authenticationException.Expires.ToString("o"));
                            context.ErrorDescription = $"The token expired on {authenticationException.Expires.ToString("o")}";
                        }

                        return context.Response.WriteAsync(JsonSerializer.Serialize(new
                        {
                            error = context.Error,
                            error_description = context.ErrorDescription
                        }));
                    }
                };
            });

            services.AddWatchDogServices(opt =>
            {
                opt.IsAutoClear = true;
                opt.ClearTimeSchedule = WatchDogAutoClearScheduleEnum.Monthly;
            });

            services.AddControllers();

            services.AddSingleton<IJWTAuthManager, JWTAuthManager>();
            
            var mapperConfig = new MapperConfiguration(mc => { mc.AddProfile(new MappingProfile()); });
            
            IMapper mapper = mapperConfig.CreateMapper();
            
            services.AddSingleton(mapper);
            
            services.AddLogging();
            
            services.AddFluentValidation(fv => { fv.RegisterValidatorsFromAssemblyContaining<LoginRequestModelValidator>(); });
            
            services.AddCors(options => options.AddDefaultPolicy(builder => builder.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin()));
            
            services.Configure<GzipCompressionProviderOptions>(options => options.Level = CompressionLevel.Optimal);
            
            services.AddResponseCompression(options =>
            {
                options.EnableForHttps = true;
                options.Providers.Add<GzipCompressionProvider>();
            });
            
            services.Configure<ApiBehaviorOptions>(options => { options.SuppressModelStateInvalidFilter = true; });

            services.AddSwaggerGen(c =>
            {
                c.EnableAnnotations();
                c.SwaggerDoc("v1", new OpenApiInfo
                {
                    Title = "xxx",
                    Version = "v1",
                    Description = "xxx",
                    Contact = new OpenApiContact
                    {
                        Name = "xxx",
                        Email = "xxx",
                        Url = new Uri("xxxx")
                    },
                });

                c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme()
                {
                    Name = "Authorization",
                    Type = SecuritySchemeType.ApiKey,
                    Scheme = "Bearer",
                    BearerFormat = "JWT",
                    In = ParameterLocation.Header,
                    Description = "Example: \"Bearer 12345abcdef\"",
                });

                c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {
                      new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme,
                                Id = "Bearer"
                            }
                        },
                        new string[] {}
                }});

                c.OperationFilter<SwaggerFileOperationFilter>();
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                c.IncludeXmlComments(xmlPath);
            });

            services.AddHangfire(configuration => configuration
                    .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                    .UseSimpleAssemblyNameTypeSerializer()
                    .UseRecommendedSerializerSettings()
                    .UseSqlServerStorage(Configuration.GetConnectionString("HangfireConnection"), new SqlServerStorageOptions
                    {
                        CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
                        SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
                        QueuePollInterval = TimeSpan.Zero,
                        UseRecommendedIsolationLevel = true,
                        DisableGlobalLocks = true
                    }));

            services.AddHangfireServer();

            return CastleWindsorResolver.Load(services);
        }

        public void Configure(IApplicationBuilder app, IBackgroundJobClient backgroundJobs, ILoggerFactory loggerFactory)
        {
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseStatusCodePages();
            app.UseSwagger();
            app.UseSwaggerAuthorized();
            app.UseCors();
            app.UseResponseCompression();
            
            app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "xxxx v1"));
            //app.UseSwaggerUI(c => c.SwaggerEndpoint("/API/xxx/swagger/v1/swagger.json", "xxxx v1"));
           
            app.UseHangfireDashboard("/hangfire", new DashboardOptions
            {
                DashboardTitle = "Job Server",
                Authorization = new[]{new HangfireCustomBasicAuthenticationFilter{User = "1",Pass = "1"}}
            });

            var cultureInfo = new CultureInfo("tr-TR");
            cultureInfo.NumberFormat.CurrencySymbol = "₺";

            CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
            CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;

            loggerFactory.AddProvider(new FileLogProvider());
            
            app.UseEndpoints(endpoints => { endpoints.MapControllers(); endpoints.MapHangfireDashboard(); });

            app.UseWatchDogExceptionLogger();
            app.UseWatchDog(opt =>
            {
                opt.WatchPageUsername = "1";
                opt.WatchPagePassword = "1";
            });
        }

**Comment by rkaptan** [comment]
Log records of methods are not visible on watchdog after authorizing.

**Comment by rkaptan** [comment]
You have any idea?

**Comment by IzyPro** [comment]
Hi @rkaptan 
A new version v1.3.1 that fixes this issue has been published. Update your package and you should be good to go.
Here's a sample middleware order that worked perfectly for me...
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, TraceRContext context)
{
	context.Database.Migrate();
	app.UseCors("CorsPolicy");

	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}

	app.UseHttpsRedirection();

	app.UseSwagger();

	app.UseSwaggerUI(c =>
	{
		c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
		c.RoutePrefix = string.Empty;
	});

	app.UseWatchDog(opt =>
	{
		opt.WatchPageUsername = "admin";
		opt.WatchPagePassword = "admin";
	});

	app.UseAuthentication();

	app.UseRouting();

	app.UseAuthorization();

	app.UseEndpoints(endpoints =>
	{
		endpoints.MapControllers();
	});
}
```
