### ISSUE TITLE
Can we link all the logs from Serilog to WatchDog

### ISSUE THREAD

**Issue by karteekmalla** [IzyPro/WatchDog#53]
**Is your feature request related to a problem? Please describe.**
This is a very good which can be used in dev and test environments 
To save cost of routing the logs to any 3rd party distributed systems can we route all the logs written by serilog to watchdog 
Is this feature already there ??  

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IzyPro** [comment]
Hi @karteekmalla 
Unfortunately, that is not available at the moment
