### ISSUE TITLE
SubFolder Problem

### ISSUE THREAD

**Issue by rkaptan** [IzyPro/WatchDog#56]
Hello,

Thank you very much for the new version. I am running my project in Subfolder. No watchdog access.

example : domain.com/API/Project/watchdog
![watchdog](https://user-images.githubusercontent.com/4254373/183630060-d7bbbdf3-f285-49c1-966a-fbbf789be806.PNG)

 - Project Type: Web API
 - Framework Version [.NET 6]
 - WatchDog Version [1.3.1]
 - Database [Default]

**Comment by syedtahasohail** [comment]
Hi, 
I have encountered the same issue also? Appreciate if someone can assist.

**Comment by Khelechy** [comment]
Thanks , we are currently investigating and fixing the issue

**Comment by rkaptan** [comment]
Have any news?

**Comment by rkaptan** [comment]
@Khelechy

**Comment by rkaptan** [comment]
Have any news?

**Comment by AMIGONA100** [comment]
This problem has not been resolved: 
https://localhost:85/login-page-is-not-displayed/ApiWatchDog/watchdog

Analyzing the operation of WatchDog I discovered that I can see the information without having the username and password.
https://localhost:7270/WTCHDwatchpage
https://localhost:7270/WTCHDwatchpage/Exceptions
https://localhost:7270/WTCHDwatchpage/Logs

I'll have to tinker with your project to improve these issues and add a column to identify the different APIs I have.

**Comment by AMIGONA100** [comment]
Solucione mi problema con los siguientes pasos pero sería bueno agregar esta ruta por parámetro:

1. Descargue el proyecto de la rama main
2. Elimine librería NuGet WatchDog de mi propia solución.
3. Agregue solamente proyecto WatchDog a mi propia solución
4. En la página index.html edite lo siguiente:

![image](https://user-images.githubusercontent.com/90100703/209019662-1069042e-8b33-4552-a796-2bad6f050110.png)

![image](https://user-images.githubusercontent.com/90100703/209020561-c93c7985-9746-4d9f-9274-87e47f91c68b.png)

![image](https://user-images.githubusercontent.com/90100703/209020617-0a81aa62-039c-40af-b15b-cb499ce369d5.png)

![image](https://user-images.githubusercontent.com/90100703/209020679-3688e53e-1def-4d39-a554-fb871fefadff.png)

![image](https://user-images.githubusercontent.com/90100703/209020744-43e94e7a-0a91-4772-ac22-61a6f7cc155b.png)

![image](https://user-images.githubusercontent.com/90100703/209020858-6f188106-4420-4c73-9e36-ddc212425d2a.png)

Esta genial este proyecto, apenas tenga tiempo voy a implementar esta ruta por parámetro y subo el cambio para aportarles con algo.
Espero les sirva, saludos

**Comment by AMIGONA100** [comment]
> Thanks , we are currently investigating and fixing the issue

Hello

**Comment by kolaval** [comment]
Same issue.
I suspect it has to do with the app path?
When you run via VS it works eg. https://localhost:1234/**myapp**/watchdog

When you deploy your app to eg. https://server/**myapp**/ and run https://server/**myapp**/watchdog you get:
Console log: [2023-01-16T05:28:12.695Z] Information: Normalizing '/wtchdlogger' to 'https://server/wtchdlogger'.
Network inspect: 
Request URL: https://server/wtchdlogger/negotiate?negotiateVersion=1
Request URL: https://server/WTCHDwatchpage?pageNumber=1&searchString=&verbString=&statusCode=
etc

All without **myapp**

**Comment by IzyPro** [comment]
@rkaptan @kolaval @syedtahasohail @AMIGONA100 
Kindly upgrade your package to the just-released 1.4.0.
Let us know if the issue persists after that.

**Comment by IzyPro** [comment]
@AMIGONA100 
You might want to check out the updates.
Some of the things you mentioned have been added
