### ISSUE TITLE
Blazor Server project

### ISSUE THREAD

**Issue by byrialsen** [IzyPro/WatchDog#57]
**Description**
After adding WatchDog logging to a Blazor Server project the Blazor parts stops working. I assume it could be related to the order in my ```Program.cs```. The WatchDog logger page is actually working, just not the original project pages.

Here is my  ```Program.cs``` (look for WATCHDOG 1-3 comments):

```csharp
using Microsoft.AspNetCore.Hosting.StaticWebAssets;
using MudBlazor.Services;
using MudBlazorServerPoc.Data;
using WatchDog;
using WatchDog.src.Enums;

var builder = WebApplication.CreateBuilder(args);

StaticWebAssetsLoader.UseStaticWebAssets(builder.Environment, builder.Configuration);

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();
builder.Services.AddSingleton<WeatherForecastService>();
builder.Services.AddMudServices();

// WATCHDOG 1
builder.Services.AddWatchDogServices(opt =>
{
    opt.IsAutoClear = true;
    opt.ClearTimeSchedule = WatchDogAutoClearScheduleEnum.Monthly;
});

var app = builder.Build();

// WATCHDOG 2
app.UseWatchDogExceptionLogger();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();

app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

// WATCHDOG 3
app.UseWatchDog(opt =>
{
    opt.WatchPageUsername = "admin";
    opt.WatchPagePassword = "admin";
});

app.Run();
```

**Comment by IzyPro** [comment]
Hi @byrialsen 
I don't understand what you mean by the statement "the blazor part stops working".
Do you mean your views no longer display content?
If so, we had a similar issue (https://github.com/IzyPro/WatchDog/issues/35) for an MVC project and the fix was simply adding `app.UseMvcWithDefaultRoute()` to the configure method.
Check the linked issue and let us know if it helps.

**Comment by byrialsen** [comment]
Hi @IzyPro.

Yes I meant no content was displayed anymore. 😀

Adding the ```app.UseMvcWithDefaultRoute()``` fixes the problem 👍. Only thing is that I am new to web technologies and a little bit confused if this call will change routing stuff in generel in the application.

**Comment by IzyPro** [comment]
Hi @byrialsen 
That's good to hear.
