### ISSUE TITLE
See logs as anonymous

### ISSUE THREAD

**Issue by byrialsen** [IzyPro/WatchDog#59]
Could it be an idea to remove the need for username/password to access WatchDog loggings.

**Comment by IzyPro** [comment]
That was enforced for security reasons.
Removing it would mean anyone with your URL being able to access your logs which is not ideal especially with applications in production.

PS: You could save the username and password in your browser so you don't have to enter it everytime

**Comment by byrialsen** [comment]
@IzyPro 

Ok, point taken to save username/password in the browser. 👍

But to be honest I don't think it should be up to a logging framework to decide if username/password is needed. I think it would be nice to have username/password as optional.
