### ISSUE TITLE
Consider fields with data type and lengthVARCHAR(max)

### ISSUE THREAD

**Issue by alexespejoch** [IzyPro/WatchDog#60]
**Description**
First of all congratulations for the tool, it is very helpful.
I am integrating to an enterprise system, and I am having problems with the length of the fields in the WatchDog tables.

Consider the length to VARCHAR(max) the following fields:

**Table: WatchLog**
responseBody    VARCHAR(max),
requestBody     VARCHAR(max),
queryString     VARCHAR(max),
path            VARCHAR(max),
requestHeaders  VARCHAR(max),
responseHeaders VARCHAR(max),
method          VARCHAR(100),
                                  
**Table: WatchLogException**
message       VARCHAR(max),
stackTrace    VARCHAR(max),
typeOf        VARCHAR(mx),
source        VARCHAR(max),
path          VARCHAR(max),
method        VARCHAR(100),
queryString   VARCHAR(max),
requestBody   VARCHAR(max),
encounteredAt VARCHAR(max)

**Comment by IzyPro** [comment]
This was a huge oversight
Thanks for reporting this @alexespejoch, it will be added to the next release

**Comment by IzyPro** [comment]
Hi @alexespejoch 
A new version (v1.3.2) with the fix has been released. Update the WatchDog.NET package in your project and you should be good to go.
