### ISSUE TITLE
How to integrate Watch Dog with Typed HttpClient Client  with IHttpClientFactory

### ISSUE THREAD

**Issue by ksarankumar** [IzyPro/WatchDog#64]
How do we integrate Watch Dog with Typed HttpClient   with IHttpClientFactory ?

I'm working with.NET6 API, this API endpoint internally invokes an external API using httpclient . Need to log stream the request and response for these external API calls and any exceptions if any. Is it possible with Watch Dog? Any help is appreciated.

**Comment by IzyPro** [comment]
Hi @ksarankumar 
It is not supported at the moment but it is something we can look into for future updates.

**Comment by ksarankumar** [comment]
thanks @IzyPro
