### ISSUE TITLE
Log display exception

### ISSUE THREAD

**Issue by liuyanruidx** [IzyPro/WatchDog#66]
![image](https://user-images.githubusercontent.com/8807436/196711397-cc1a44ea-72f1-4498-bd25-9a57c293e546.png)

**Comment by ahror1997** [comment]
show the code

**Comment by zhaoyangguang** [comment]
me too

**Comment by IzyPro** [comment]
Kindly report issues using the template so we have enough information to work with

**Comment by liuyanruidx** [comment]
Code:

builder.Services.AddWatchDogServices(opt =>
{
    opt.IsAutoClear = true;
    opt.SetExternalDbConnString = builder.Configuration.GetConnectionString("TestDB");
    opt.SqlDriverOption = WatchDogSqlDriverEnum.PostgreSql;
});

Details:
Project Type: ASP.NET Core API
Framework Version: .NET 6
WatchDog Version: 1.3.2
Database: Postgres 15.0

**Comment by IzyPro** [comment]
What browser are you using?
And have you tried it with other browsers?
Also, do you have any json formatter or anything similar on your API?

**Comment by liuyanruidx** [comment]
Yes,you are right, I used  json formatter. Now,It works. Thinks!

**Comment by liuyanruidx** [comment]
> What browser are you using? And have you tried it with other browsers? Also, do you have any json formatter or anything similar on your API?

**Comment by liuyanruidx** [comment]
> What browser are you using? And have you tried it with other browsers? Also, do you have any json formatter or anything similar on your API?

Yes,you are right, I used json formatter. Now,It works. Thinks!
