### ISSUE TITLE
logs orders by time and line of code inCode page 

### ISSUE THREAD

**Issue by AbdullahElamir** [IzyPro/WatchDog#69]
when i work on clojure function i add some logs inCode but i can't order by code line or time
![لقطة شاشة_١٤٤٤٠٣٢٦_٠١٣٦٥٢](https://user-images.githubusercontent.com/10694513/197337082-bfedb992-fb00-4eb2-af67-797c20203038.png)

**Comment by IzyPro** [comment]
Hi @AbdullahElamir 
The logs are ordered by time automatically.
We also plan to add more options to filter and order in-code logs in future updates.
