### ISSUE TITLE
WatchDogUi not working with AuthorizeFilter

### ISSUE THREAD

**Issue by aslandgn** [IzyPro/WatchDog#71]
I clearly add the code snippets according to readme. 
I work with AuthorizeFilter as you see in first screenshot.
This filter blocks the requests.
When I try without this filter, I can access the Watchdog controller.

![image](https://user-images.githubusercontent.com/22791789/198006004-2471b67f-8260-4002-8c4e-16d54cadfd0a.png)

![image](https://user-images.githubusercontent.com/22791789/198006289-7296f670-a42e-4e8b-9595-f1db1f04c4e1.png)

Project Type: Web API
Framework Version [.NET 3.1]
WatchDog Version [1.3.2]
Database MSQL

**Comment by IzyPro** [comment]
Hi @aslandgn 
A potential fix for this issue has just been published in the pre-release version (v1.3.3-rc). Do update and let us know how that goes
