### ISSUE TITLE
CORS Issue after Implementing Watchdog

### ISSUE THREAD

**Issue by shyamjith-fingent** [IzyPro/WatchDog#76]
**Description**
It looks like Watchdog Overrides the CORS policy defined, so I am getting CORS Error for each API Calls

 string WatchDogUserName = builder.Configuration.GetSection("WatchDog:WatchDogUserName").Value.ToString();
    string WatchDogPassword = builder.Configuration.GetSection("WatchDog:WatchDogPassword").Value.ToString();
    app.UseWatchDogExceptionLogger(); // Add Exception logging

    app.UseWatchDog(options =>
    {
        options.WatchPageUsername = WatchDogUserName;
        options.WatchPagePassword = WatchDogPassword;
  
    });

If I Comment above line the CORS policy issue disappeared and APIs are working fine on the Origins which are defined in the CORS Policy

Project Type: Web API
Framework Version [.NET 6]
WatchDog Version [1.3.2]
Database [Default]

**Comment by IzyPro** [comment]
Hi @shyamjith-fingent 
Have you tried switching the middleware order?
Let app.UseCors() come before/after watchdog middleware
If that doesn’t work, share a sample of your middleware order and cors policy so we can replicate on our end and fix if necessary

**Comment by shyamjith-fingent** [comment]
@IzyPro : The issue is weird , It started working after adding app.UseCors()  before and after  watchdog middleware

**Comment by IzyPro** [comment]
Hi @shyamjith-fingent 
A new property (CorsPolicy) has been added to .UseWatchDog() in the just released v1.3.3 that let’s you pass the name of your policy
Do check it out and let us know how it goes
