### ISSUE TITLE
watchdog ui undefined when newton json  with DefaultContractResolver setting

### ISSUE THREAD

**Issue by KimMeng2015** [IzyPro/WatchDog#80]
`  .AddNewtonsoftJson(options =>
                {
                  
                    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;

                    options.SerializerSettings.ContractResolver = new DefaultContractResolver();

                    options.SerializerSettings.DateFormatString = config.JsonDateFormat;
                })`

will   get below  undefinded info .
![image](https://user-images.githubusercontent.com/17702302/202374126-1bab25e0-c563-434c-96b4-b6a5c2b7e022.png)

and   this is required  in my project.

`options.SerializerSettings.ContractResolver = new DefaultContractResolver();`

**Details (please complete the following information):**
 - Project Type: [MVC]
 - Framework Version [e.g. .NET Core 3.1]
 - WatchDog Version [1.3.2]
 - Database [e.g Default,]
 - Browser [e.g Chrome, Edge]

**Comment by IzyPro** [comment]
Hi @KimMeng2015 
A new property (serializer) has been added to .UseWatchDog() in the just released v1.3.3 that lets you specify the converter type if you are using a global json serializer/converter
You can check the readme for more information
