### ISSUE TITLE
Memory usage with watchdog UI

### ISSUE THREAD

**Issue by damienheckler** [IzyPro/WatchDog#82]
Hi,

I have a web api in production with around 6000 requests by day.

The memory usage for this process is about 150MB but when I open the Watchdog UI the memory usage is exploding until 3GB before showing the first page of requests.

In case this bug cannot be quickly fixed?

Or maybe can you add an option Hourly in the enum WatchDogAutoClearScheduleEnum?
So I will have the option to keep watchdog logs for the last hour only to reduce the memory impact

Thanks.

Project Type: Web API
Framework Version [.NET 6]
WatchDog Version [1.3.2]
Database MSQL
Browser : Chrome

**Comment by IzyPro** [comment]
Hi @damienheckler 
Some optimizations were done in the just released v1.3.3
Do upgrade and let us know if that fixes your memory issue.
Otherwise, more options have been added yo clear logs hourly, every 6 hours and every 12 hours
