### ISSUE TITLE
WatchDog ExceptionLogger Not Working with Asp.Net Global Exception Filter

### ISSUE THREAD

**Issue by wnilsson** [IzyPro/WatchDog#87]
**Description**
For my Web Api app, WatchDog does not log exceptions when I also use a global exception filter i..e
builder.Services.AddControllers(opt => opt.Filters.Add(new ExceptionHandlerFilter()));
But if I do not inject the exception filter, WatchDog logs all exceptions successfully.

**To Reproduce**
For now the filter only has this basic code but I plan to change so the responses are managed properly:

public class ExceptionHandlerFilter : IExceptionFilter, IOrderedFilter
{
    public int Order => int.MaxValue - 10;

    public void OnException(ExceptionContext context)
    {
        context.Result = new StatusCodeResult(StatusCodes.Status500InternalServerError);
        context.ExceptionHandled = true;            
    }
}

**Expected behavior**
WatchDog should still log the exception when using a global exception filter

**Screenshots**
N/A

**Details (please complete the following information):**
 - Project Type: ASP.Net Web API
 - Framework Version .NET 6
 - WatchDog Version 1.3.2
 - Database MSSQL
 - Browser Chrome

**Comment by IzyPro** [comment]
@wnilsson 
Do you mean when you use the exception filter, WatchDog doesn’t log any exceptions at all or it just doesn’t log the exceptions caught by your filter?
Kindly provide clarity on this

**Comment by wnilsson** [comment]
Hi @IzyPro, when I use a global exception filter, WatchDog doesn't log any exceptions at all i.e. even if I step over the logic in my filter, there is no exception shown in the Exceptions Log page.

**Comment by Cipri18** [comment]
Hi. It happen also to me. If I use UseWatchDog and my GlobalErrorHandler, it stop logging exceptions. Only works when I disable my custom GlobalErrorHandler...

**Comment by IzyPro** [comment]
Registering a global exception handler/filter means you are already handling your exceptions.
WatchDogExceptionLogger only captures exceptions when they are thrown and not handled.
You can either remove the exception filter or log the details as an error (WatchLogger.LogError) so you can view it in your logs.
