### ISSUE TITLE
InvalidOperationException: Property 'JsonResult.SerializerSettings' must be an instance of type 'Newtonsoft.Json.JsonSerializerSettings'.

### ISSUE THREAD

**Issue by Cipri18** [IzyPro/WatchDog#94]
**Description**
The watchdog page list exception suddenly stopped logging. Doesn't log anything, I watch on my database and everything its logging ok, but visually on the page not. 

**To Reproduce**
1. Go to watchdog page
2. Inspect page and look for console logs, there's 500 https responses calls.
4. No error exceptions throws on my code.

**Screenshots**
![image](https://user-images.githubusercontent.com/92941158/211038603-6db70297-97eb-4be3-b342-ab0ee1dfd731.png)
![image](https://user-images.githubusercontent.com/92941158/211038641-ab2847db-473b-4b51-a5b6-82f305518fb2.png)
![image](https://user-images.githubusercontent.com/92941158/211038742-af6d4267-ecc9-4a84-a20d-ef50e094c59a.png)

**Details (please complete the following information):**
 - Project Type: API
 - Framework Version : NET 6
 - WatchDog Version : 1.3.3
 - Database MSSQL
 - Browser : BRAVE/CHROME

**Comment by IzyPro** [comment]
Hi @Cipri18 
Looks like your api uses Newtonsoft as a global json serializer/converter.
You need to specify that while setting up WatchDog.
See the optional configuration section of the documentation for more details.

**Comment by Cipri18** [comment]
@IzyPro You're right. Fixed.
opt.Serializer = WatchDogSerializerEnum.Newtonsoft;
