### ISSUE TITLE
Watchdog login has no security

### ISSUE THREAD

**Issue by edwinjoy69** [IzyPro/WatchDog#95]
**Description**
When trying to access watchdog first it shows the login screen if the login url is without authentication in swagger.
we can easily close the login screen by using 'display : none' option .its not that safe can you guys fix that issue.

**To Reproduce**
1. Go to 'watchdog URL then go to logon screen'
2. Click on 'Inspect on the page the  Hide it by using CSS'
3. Scroll down to 'Then you can easily see all the details'

**Expected behavior**
if he or she hides using any options like JS or CSS then dont allow them to see the exceptions and all.

**Screenshots**

**Details (please complete the following information):**
 - Project Type: [e.g. API, MVC]
 - Framework Version [e.g. .NET Core 3.1, .NET 6]
 - WatchDog Version [e.g. 1.3.0, 1.2.1]
 - Database [e.g Default, MySQL]
 - Browser [e.g Chrome, Edge]

**Additional context**

**Comment by Khelechy** [comment]
This has been fixed and will be resolved when you upgrade the package to v1.40 that is going to be released soon. Thanks

**Comment by shyamjith-fingent** [comment]
@Khelechy : Could you please let us know v1.4.0 release date ?
