### ISSUE TITLE
Need to hide the Watchdog UI

### ISSUE THREAD

**Issue by edwinjoy69** [IzyPro/WatchDog#96]
**Is your feature request related to a problem? Please describe.**
Need to hide the watchdog UI still its need to be logged in DB.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Khelechy** [comment]
Can you be a bit clear with what you described please .

**Comment by shyamjith-fingent** [comment]
I think he was saying , do we have any option to Enable or disable the Watchdog UI alone. All the logging features should work , just we need to hide the UI in production environment. we will just enable the UI for a specific period in a day to monitor all Logs & exceptions.

**Comment by edwinjoy69** [comment]
Yes exactly like this.

**Comment by IzyPro** [comment]
There is no option to do that at the moment
@edwinjoy69 is there a specific reason why you would want that?

**Comment by fmd-aggne** [comment]
if (app.Environment.IsDevelopment())
    {
....
}

Should help with this for an ASP.NET Core project.
