### ISSUE TITLE
not rendered html pages after implemeting watchdog

### ISSUE THREAD

**Issue by Fraeng** [IzyPro/WatchDog#97]
**Description**
not rendered html pages after implemeting watchdog 1.3.3

**To Reproduce**
1. add empty aspnet core 6 api project  (VS Version 17.4.3)
2. add wwwroot with html stuff
3. add watchdog
4. html content are not rendered anymore

**Comment by IzyPro** [comment]
@Fraeng we had a similar issue here, let us know if that doesn't work for you
https://github.com/IzyPro/WatchDog/issues/57

**Comment by Fraeng** [comment]
@IzyPro  thanks for the hint. I have found the problem. Was my mistake. 
I had added Authentication option before app.MapControllers().
Didn't notice since everything worked except html files.
